---

# Configuration directives for Travis CI
# --------------------------------------
# See the Travis documentation for help on writing this file.

# [Travis CI] http://travis-ci.org
# [configuration] http://about.travis-ci.org/docs/user/build-configuration/


language: python  # Needed to run ansible

python:
  - "2.7"

install:
  - pip install ansible shade shade-ansible
  - pip install ansible-lint
  - pip install yamllint

script:
  # Syntax check every ansible playbook in root
  # Don't check main, though, as vars_prompt still
  # trigger during syntax checks, and travis fails
  - yamllint $(git ls-files '*.yaml' '*.yml')
  - ansible-lint $(git ls-files '*.yaml' '*.yml')
  # XXX Check ansible syntax
  # ansible-playbook --syntax-check -i inventory
