---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Set server hostname
      hostname: name="{{ server_fqdn }}"

    - name: Disable firewalld service
      systemd: name=firewalld enabled=no state=stopped

    - name: Disable NetworkManager service
      systemd: name=NetworkManager enabled=no state=stopped

    - name: Enable network service
      systemd: name=network enabled=yes

    - name: Install NTP package
      yum: name=ntp state=installed

    - name: Enable NTP service
      systemd: name=ntpd enabled=yes state=started

    - name: Install OpenStack {{ os_release }} repository
      yum: name=centos-release-openstack-{{ os_release }} state=installed

    - name: Install updates
      yum: name=* state=latest update_cache=yes

    - name: Install packstack installer
      yum: name=openstack-packstack state=installed

    - name: Copy server certificate
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.path }}'
        owner: root
        group: root
        mode: '{{ item.mode }}'
      with_items:
        - src: '{{ ssl_cacert }}'
          path: /etc/pki/tls/certs/os_packstack_cacert.pem
          mode: '0644'
        - src: '{{ ssl_cert }}'
          path: /etc/pki/tls/certs/os_packstack_cert.pem
          mode: '0644'
        - src: '{{ ssl_key }}'
          path: /etc/pki/tls/private/os_packstack_key.pem
          mode: '0600'

    # XXX See how SSL and httpd conf can be done
    # XXX Should we use a answer file as a template?
    #     - name: Execute packstck installer
    #       #command: packstack --allinone --os-horizon-ssl=y --os-ssl-cert=/etc/pki/tls/certs/os_packstack_cert.pem --os-ssl-key=/etc/pki/tls/private/os_packstack_key.pem --os-ssl-cachain=/etc/pki/tls/certs/os_packstack_cacert.pem --ssl-cacert-selfsign=n --nova-ssl-cert=/etc/pki/tls/certs/os_packstack_cert.pem --nova-ssl-key=/etc/pki/tls/private/os_packstack_key.pem
    #       command: packstack --allinone --os-horizon-ssl=y
    #       args:
    #         chdir: '/root'
    #         creates: '/root/keystonerc_admin'
    #  - http->https redirection in /etc/httpd/conf.d/15-horizon_vhost.conf

    # XXX Shouldn't be required if packstack is used appropriately
    - name: Fix HTTP to HTTPS redirection for Horizon
      replace:
        path: /etc/httpd/conf.d/15-horizon_vhost.conf
        regexp: 'vnode-0\.localdomain'
        replace: "{{ server_fqdn }}"
      notify:
        - restart apache

    - name: Fix HTTPS VHost for Horizon
      replace:
        path: /etc/httpd/conf.d/15-horizon_ssl_vhost.conf
        regexp: 'vnode-0\.localdomain'
        replace: "{{ server_fqdn }}"
      notify:
        - restart apache

    - name: Enable secure CSRF cookie for HTTPS in horizon settings
      lineinfile:
        dest: /etc/openstack-dashboard/local_settings
        regexp: '^#CSRF_COOKIE_SECURE'
        line: 'CSRF_COOKIE_SECURE = True'
        backup: yes
      notify:
        - restart apache

    - name: Enable secure session cookie for HTTPS in horizon settings
      lineinfile:
        dest: /etc/openstack-dashboard/local_settings
        regexp: '^#SESSION_COOKIE_SECURE'
        line: 'SESSION_COOKIE_SECURE = True'
        backup: yes
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
