---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - os_project:
        cloud: "{{ server_fqdn }}"
        state: present
        name: "{{ item.project_name }}"
        description: "{{ item.project_name }}"
        domain_id: default
        enabled: True
      with_items:
        - project_name: dteam
        - project_name: ops
        - project_name: fedcloud
