---
- hosts: localhost
  connection: local
  tasks:
    - name: Create OpenStack projects
      os_project:
        cloud: "{{ server_fqdn }}"
        state: present
        name: "{{ item.project_name }}"
        description: "{{ item.project_name }}"
        domain_id: default
        enabled: True
      with_items:
        - project_name: dteam
        - project_name: ops
        - project_name: fedcloud

    - name: Add admin as admin of OpenStack projects
      os_user_role:
        cloud: "{{ server_fqdn }}"
        user: admin
        role: admin
        project: "{{ item.project_name }}"
      with_items:
        - project_name: dteam
        - project_name: ops
        - project_name: fedcloud
